CREATE TABLE t_p445658_novel_innovation_met.apartments (
    id SERIAL PRIMARY KEY,
    internal_id VARCHAR(50) UNIQUE NOT NULL,
    type VARCHAR(50),
    category VARCHAR(50),
    rooms INTEGER,
    floor INTEGER,
    floors_total INTEGER,
    area NUMERIC(10,2),
    living_space NUMERIC(10,2),
    kitchen_space NUMERIC(10,2),
    price BIGINT,
    currency VARCHAR(10) DEFAULT 'RUR',
    renovation TEXT,
    balcony TEXT,
    bathroom_unit TEXT,
    building_name TEXT,
    building_type TEXT,
    building_state TEXT,
    building_phase TEXT,
    building_section TEXT,
    built_year INTEGER,
    ready_quarter INTEGER,
    lift BOOLEAN DEFAULT FALSE,
    parking TEXT,
    address TEXT,
    region TEXT,
    locality TEXT,
    sub_locality TEXT,
    description TEXT,
    complex_description TEXT,
    payment_methods TEXT,
    advantages TEXT,
    images TEXT[],
    sales_agent_name TEXT,
    sales_agent_phone TEXT,
    nmarket_complex_id VARCHAR(50),
    nmarket_building_id VARCHAR(50),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);